apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tomcoolpxl/argocd-config.git
    targetRevision: master
    path: environments/production
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Manual sync for production (no automated section)